### PR TITLE
OPL-31: Create 'createInvoice' service in Contract module

### PR DESCRIPTION
**Pull request by sniedzielski**
TICKET: https://openimis.atlassian.net/browse/OPL-31

such mutation (implemented service is wrapped here) creates invoices for chosen contract
Screenshot from 2021-11-09 11-26-09
:

### CODE REVIEW

**Comment by delcroip** [comment]
@dragos-dobre , this is what we discussed, should we create invoice automatically based on signal instead of the the this contributuion? the only drawback of signals is that we cannot have "Invoices" that cover severals contract (like per PH)

**Comment by dragos-dobre** [comment]
@delcroip I think this is a good solution. I don't find any issue to have invoice per contract and not include multiple contracts in one invoice. It is even obvious to have an invoice per contract.

**Comment by sniedzielski** [comment]
@delcroip @dragos-dobre My question is: which solution will be used? This one from that PR with selecting some contracts and generate fot then 'invoice' or via signal (we can use signal approve contract and create invoice)?
In case of second approach I will need change this PR.

**Comment by delcroip** [comment]
> 
> 
> @delcroip @dragos-dobre My question is: which solution will be used? This one from that PR with selecting some contracts and generate fot then 'invoice' or via signal (we can use signal approve contract and create invoice)? In case of second approach I will need change this PR.

We will use the approach from that PR

**Review by delcroip — APPROVED** [review]

**Pull request merged**
